services:
  db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noticias-360-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - noticias-360-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:1337/dashboard || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./public:/app/public
    networks:
      - noticias-360-network

volumes:
  db-data:

networks:
  noticias-360-network:
    driver: bridge
